# 09- Built-in Module: Numpy

NumPy is a powerful Python library for scientific computing. It manages n-dimensional array object, linear algebra operations, Fourier transform, and random number, ...


### 9.1. Creation of an array and basic properties and operations

In [2]:
import numpy as np

In [3]:
x=[10, 20, 5, 0]
y=[0, 4, 5, 10]

Convert a list to an array:

In [4]:
a=np.array(x)
a

array([10, 20,  5,  0])

In [5]:
len(a)

4

What will be the length of the following array?

In [6]:
len(np.array([[10, 20, 5, 0], [0, 4, 5, 10]]))

2

Create an array with a precise type of data

In [7]:
np.array([10.4, 2, 4], dtype=int)

array([10,  2,  4])

What will happen to:

In [8]:
np.array(['b', 2, 4], dtype=int)

ValueError: invalid literal for int() with base 10: 'b'

Do you still remember the difference between list and array? Describe it by an example with Python.

An array can contain any type of data

In [9]:
t=np.array([(1,2,3), (4,5,6)], dtype=tuple)
t

array([[1, 2, 3],
       [4, 5, 6]], dtype=object)

 **Any idea on why it is printed as an array of list instead?**

What can be the output of this:

In [10]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Get the number of axes (dimensions) of an array. In the Python, the number of dimensions is referred to as rank.

In [19]:
a.ndim

2

Get the size of an array in each dimension

In [111]:
a.shape

(4, 5)

Get the type of elements of an array

In [20]:
a.dtype.name

'int64'

Get the size in bytes of each element of an array

In [21]:
a.itemsize

8

Get the total number of elements of an array.

In [115]:
a.size

20

In [116]:
type(a)

numpy.ndarray

### 9.2. Arithmetic and logic operators

In [22]:
a = np.array([20,30,40,50])
b = np.arange(4)

In [23]:
a-b

array([20, 29, 38, 47])

In [24]:
a*b

array([  0,  30,  80, 150])

In [147]:
a**3

array([  8000,  27000,  64000, 125000])

In [138]:
a+b

array([20, 31, 42, 53])

In [139]:
b**2

array([0, 1, 4, 9])

In [141]:
a<40

array([ True,  True, False, False], dtype=bool)

### 9.3. Mathematical operations

In [28]:
B = np.arange(3)
C = np.array([2., -1., 4.])

In [29]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [30]:
np.add(B, C)

array([ 2.,  0.,  6.])

In [31]:
np.abs(-10), np.amin(x), np.amax(x), np.argmin(x)

(10, 0, 20, 3)

In [32]:
10*np.sin(B)

array([ 0.        ,  8.41470985,  9.09297427])

In [149]:
np.floor(2.5), np.ceil(2.5)

(2.0, 3.0)

**Deal with axes**

In [63]:
A=np.array([[1, 2, 3], [2, 2, 0], [4, 2, 3], [0,1, 2]])
A

array([[1, 2, 3],
       [2, 2, 0],
       [4, 2, 3],
       [0, 1, 2]])

In [64]:
np.mean(A)

1.8333333333333333

What aboout the mean of each column or row of A?

In [65]:
np.mean(A, axis=0)

array([ 1.75,  1.75,  2.  ])

In [68]:
np.mean(A, axis=1)

array([ 2.        ,  1.33333333,  3.        ,  1.        ])

**Use of numpy for metrics**

In [34]:
def chebychevMetric(x, y):
    p=len(x)
    delta=[np.abs(x[i]-y[i]) for i in range(p)]
    return np.max(delta) 

In [35]:
chebychevMetric(x, y)

16

In [36]:
def euclideanMetric(x, y):
    delta=0.0
    p=len(x)
    for i in range(p):
        delta+=np.power(x[i]-y[i],2)
    return np.sqrt(delta)

In [37]:
euclideanMetric(x, y)

21.354156504062622

In [38]:
def mahalanobisMetric(covarianceMatrix, x, y):
    delta=0
    xy_vector=np.subtract(np.array(x), np.array(y))
    xy_tvector=xy_vector.transpose()
    delta=np.dot(np.dot(xy_vector, covarianceMatrix), xy_tvector)
    return np.sqrt(delta)

In [39]:
data=[x, y, [0,0,0,1], [4,4,6,1]]
covarianceMatrix=np.cov(data)
mahalanobisMetric(covarianceMatrix, x, y)

76.75067860720624

### 9.4. Linspace function.

In [90]:
np.linspace(2.0, 3.0, num=5)  

array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])

In [91]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([ 2. ,  2.2,  2.4,  2.6,  2.8])

In [92]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ]), 0.25)

### 9.5. Linear algebra tools

Numpy provides tools to compute: vector or matrix norm, inverse of a square matrix, solve a linear system of equations, determinant of a square matrix, solve linear least-squares problem, pseudo-inverse (Moore-Penrose) calculated using a singular value decomposition and Integer power of a square matrix.

#### 9.5.1. Matrix

Create a list of lists named a

In [41]:
a=[[1, 2, 3], [1, 0, 2], [-5, 4, 3]]
a

[[1, 2, 3], [1, 0, 2], [-5, 4, 3]]

Convert the list *a* to a matrix *b*

In [42]:
b=np.matrix(a)
b

matrix([[ 1,  2,  3],
        [ 1,  0,  2],
        [-5,  4,  3]])

Get the inverse of matrix *b*

In [43]:
np.linalg.inv(b)

matrix([[ 0.36363636, -0.27272727, -0.18181818],
        [ 0.59090909, -0.81818182, -0.04545455],
        [-0.18181818,  0.63636364,  0.09090909]])

and its determinant

In [44]:
np.linalg.det(b)

-21.999999999999996

Transpose of matrix *b*

In [45]:
np.transpose(b)

matrix([[ 1,  1, -5],
        [ 2,  0,  4],
        [ 3,  2,  3]])

Trace of *b* (What is a trace of a matrix?)

In [46]:
np.trace(a)

4

#### A) Types of matrices

Diagonal matrix

In [47]:
diag = np.diag((1, 2, 3))
diag

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

Upper triangle of a matrix. It returns a copy of a matrix with the elements below the $k$-th diagonal

In [48]:
A=np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.triu(A, k=0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [49]:
np.triu(A, k=1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

What about lower triangle matrix?

Matrix filled with zeros, ones and empty

In [50]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [51]:
np.ones((2,3), dtype=np.int16 ) 

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [52]:
np.ones((2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

Random matrix

In [53]:
np.random.random((2,3))

array([[ 0.47528756,  0.34719603,  0.51290906],
       [ 0.79829139,  0.59885001,  0.18517346]])

#### B) Eigen values and vectors

In [102]:
v, w=np.linalg.eig(A)

In [103]:
v

array([  1.61168440e+01,  -1.11684397e+00,  -1.30367773e-15])

In [104]:
w

matrix([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]])

#### C) Element wise multiplication

Given A, B by

In [54]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )

Given two matrices A, B, what is the difference between the following two operations?

In [55]:
A*B

array([[2, 0],
       [0, 4]])

and

In [56]:
A.dot(B)

array([[5, 4],
       [3, 4]])

#### 9.5.2. Linear system of equations

$\begin{cases} 2x_1 + 4x_2 + 5x_3=4 \\ x_1 + x_2 + x_3=0 \\ 4x_1 +x_2+ 2x_3=2 \end{cases}$ 

In [19]:
A = np.array([[2, 4, 5], [1,1, 1], [4,1, 2]])
b = np.array([4,0, 2])
x = np.linalg.solve(A, b)

In [20]:
x

array([-0.4, -2.8,  3.2])

Check whether the answer is correct

In [21]:
np.allclose(np.dot(A, x), b)

True

### 9.6. Complex numbers

In [26]:
number=np.complex(2, 3)
number

(2+3j)

In [27]:
type(number)

complex

In [32]:
number.real, number.imag

(2.0, 3.0)

In [33]:
number.__abs__()

3.605551275463989

In [35]:
number.__pow__(2)

(-5+12j)

In [105]:
2*number

(4+6j)

An array of complex numbers

In [117]:
cnumbers = np.array( [ [1,2, 4+2j], [1+2j,2, 4+2j], [3,4, 3] ], dtype=complex )

In [118]:
cnumbers

array([[ 1.+0.j,  2.+0.j,  4.+2.j],
       [ 1.+2.j,  2.+0.j,  4.+2.j],
       [ 3.+0.j,  4.+0.j,  3.+0.j]])

## Exercises

**Exercise 0.**

   * Propose Python code that creates a $5\times5$ matrix with values $2,4,6,8$ just below the diagonal.
   * Consider $A$ as a $(6,7,8)$ shape array, what is the index $(x,y,z)$ of the $90^\text{th}$ item?

**Exercise 1.** 

Propose Python code

  * creates a null vector N of size 20.
  * creates a ones vector O of size 20 but the fifth value which is 0
  * creates a vector A with values ranging from 12 to 53 and reverses it (first element becomes last).

**Exercise 2.** Creates a function of two matrices as parameters and returns their the product.

**Exercise 3.** Given a vector x, propose a Python code that computes its norm.

**Exercise 4.** Let

$$A = 
 \begin{pmatrix}
  1 & 4 & -3 \\
  6 & 3 & 2  
 \end{pmatrix}, \; B = 
 \begin{pmatrix}
  3 & 2 & 1 \\
  -2 & 6 & 5  
 \end{pmatrix},\;\text{and } C = 
 \begin{pmatrix}
  2 & 4 \\
  4 & 0 \\
  -2 & 2
 \end{pmatrix}.\; \text{Let }\; \alpha=4 \;\text{and}\; \beta=1/2.$$
 
Perform the following calculations:    $(1)\; A + B \;$ $(2)\; A + C\;$ $(3)\; B^t+C\;$ $(4)\; A+B^t\;$ $(5)\; \beta C\;$ $(6)\; 4A -3B\;$ $(7)\; A^t+\alpha C\;$ $(8)\; A+B-C^t\;$ $(9)\; 4A + 2B -4C^t\;$


**Exercise 5.** Extract the integer part of a random array using 5 different methods 

**Exercise 6.** Create a vector of size 10 with values ranging from 0 to 1, both excluded

**Exercise 7.** Consider two random array A anb B, check if they are equal 

**Exercise 8.** Solve the following system:
$$\begin{cases} 2x +y +3z=1 \\ 2x +6y+8z=3\\ 6x+8y+18z=5\end{cases}$$
and check its result. 

**BONUS: Python Documentation**

In [69]:
def getFunction(A, p):
    """
    Returns a...
    
    Parameters
    ----------
    A: matrix of size n x m
    p: number of
    """
    farthest=[]
    for k in range(p):
        index=np.argmax(A)
        i, j= getI(index, n, n)
        farthest.append(data[i])
        farthest.append(data[j])
        A[i, j]=0
        A[j, i]=0
    return farthest

In [70]:
help(getFunction)

Help on function getFunction in module __main__:

getFunction(A, p)
    Returns a...
    
    Parameters
    ----------
    A: matrix of size n x m
    p: number of

